spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  application:
    name: video-storage-api
  security:
    user:
      name: username
      password: password
      roles: "admin"
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      database: demodb
      uri: mongodb://127.0.0.1:27017/demodb
management:
  endpoint:
    health:
      show-components: ALWAYS
      show-details: ALWAYS
      probes:
        enabled: true
    restart:
      enabled: true
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus,loggers'
server:
  max-http-header-size: 20KB
  port: 8080
  servlet:
    context-path: /v1
